# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: agent

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    # Borrow from https://github.com/digitalocean/godo/pull/396
    - name: Format
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    - name: Setup Deno
      # uses: denoland/setup-deno@v1
      uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
      with:
        deno-version: v1.x

    # Go code requires `ks` installed globally
    - name: Install ks
      run: deno install --unstable -A --root /usr/local -n ks https://deno.land/x/kube_script/main.ts

    - name: Test
      run: go test -v ./...
